server:
  port: 8681
eureka:
  client:
    service-url:
      defaultZone:
        http://127.0.0.1:8670/eureka/ # 实际开发中建议使用域名的方式
spring:
  application:
    name: turbine
turbine:
  aggregator:
    cluster-config: default
  app-config: dashboard-ribbon,dashboard-feign
  cluster-name-expression: new String("default")
management:
  endpoints:
    web:
      exposure:
        include: ["*"]