server:
  port: 8675
spring:
  application:
    name: rest
eureka:
  client:
    service-url:
      defaultZone:
        http://127.0.0.1:8670/eureka/ # 实际开发中建议使用域名的方式
#ribbon:
#  eureka:
#    enabled: false
#stores:
#  ribbon:
#    listOfServers: example.com, baidu.com
