server:
  port: 8678
spring:
  application:
    name: hystrix-feign
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8670/eureka/ # 实际开发中建议使用域名的方式
feign:
#  okhttp:
#    enabled: true
  hystrix:
    enabled: true